CallingAPI_MVC/Models/Blog.cs
namespace CallingAPI_MVC.Models
{
    public class Blog
    {
        public int id { get; set; }
        public string title { get; set; }
        public string permalink { get; set; }
        public string date { get; set; }
        public string image_link_small { get; set; }
        public string image_link_medium { get; set; }
        public string desc { get; set; }
    }
}

CallingAPI_MVC/Models/ErrorViewModel.cs
namespace CallingAPI_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CallingAPI_MVC/Models/Post.cs
namespace CallingAPI_MVC.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; } = null!;
        public string Date { get; set; }
        public string Permalink { get; set; }
        public string Image_link_small { get; set; }
        public string Image_link_medium { get; set; }
        public string Desc { get; set; }
        public string Body { get; set; }

    }
}

CallingAPI_MVC/Models/TipsNepal.cs
namespace CallingAPI_MVC.Models
{

   

    public class TipsNepal
    {
        public int id { get; set; }
        public DateTime date { get; set; }
        public DateTime date_gmt { get; set; }
        public Guid guid { get; set; }
        public DateTime modified { get; set; }
        public DateTime modified_gmt { get; set; }
        public string slug { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public string link { get; set; }
        public Title title { get; set; }
        public Content content { get; set; }
        public Excerpt excerpt { get; set; }
        public int author { get; set; }
        public int featured_media { get; set; }
        public string comment_status { get; set; }
        public string ping_status { get; set; }
        public bool sticky { get; set; }
        public string template { get; set; }
        public string format { get; set; }
        public Meta meta { get; set; }
        public int[] categories { get; set; }
        public int?[] tags { get; set; }
        public string jetpack_featured_media_url { get; set; }
        public _Links _links { get; set; }
    }

    public class Guid
    {
        public string rendered { get; set; }
    }

    public class Title
    {
        public string rendered { get; set; }
    }

    public class Content
    {
        public string rendered { get; set; }
        public bool _protected { get; set; }
    }

    public class Excerpt
    {
        public string rendered { get; set; }
        public bool _protected { get; set; }
    }

    public class Meta
    {
        public string spay_email { get; set; }
    }

    public class _Links
    {
        public Self[] self { get; set; }
        public Collection[] collection { get; set; }
        public About[] about { get; set; }
        public Author[] author { get; set; }
        public Reply[] replies { get; set; }
        public VersionHistory[] versionhistory { get; set; }
        public PredecessorVersion[] predecessorversion { get; set; }
        public WpFeaturedmedia[] wpfeaturedmedia { get; set; }
        public WpAttachment[] wpattachment { get; set; }
        public WpTerm[] wpterm { get; set; }
        public Cury[] curies { get; set; }
    }

    public class Self
    {
        public string href { get; set; }
    }

    public class Collection
    {
        public string href { get; set; }
    }

    public class About
    {
        public string href { get; set; }
    }

    public class Author
    {
        public bool embeddable { get; set; }
        public string href { get; set; }
    }

    public class Reply
    {
        public bool embeddable { get; set; }
        public string href { get; set; }
    }

    public class VersionHistory
    {
        public int count { get; set; }
        public string href { get; set; }
    }

    public class PredecessorVersion
    {
        public int id { get; set; }
        public string href { get; set; }
    }

    public class WpFeaturedmedia
    {
        public bool embeddable { get; set; }
        public string href { get; set; }
    }

    public class WpAttachment
    {
        public string href { get; set; }
    }

    public class WpTerm
    {
        public string taxonomy { get; set; }
        public bool embeddable { get; set; }
        public string href { get; set; }
    }

    public class Cury
    {
        public string name { get; set; }
        public string href { get; set; }
        public bool templated { get; set; }
    }

}

CallingAPI_MVC/Controllers/BlogController.cs
using CallingAPI_MVC.Models;
using CommandLine.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;

namespace CallingAPI_MVC.Controllers
{
    public class BlogController : Controller
    {
  
        public IActionResult Index()
        {
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            string json = (new WebClient()).DownloadString("https://www.nepalinames.com/blog/wp-json/zooktirest/v2/posts/search/?s=a");
            var blogResult = JsonConvert.DeserializeObject(json, typeof(List<Blog>)) as List<Blog>;


            return View(blogResult);
        }
















        public IActionResult Details(int id)
        {
            return View();
        }


    }
}

CallingAPI_MVC/Controllers/HomeController.cs
using CallingAPI_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CallingAPI_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public async Task<IActionResult> Index()
        {
            var URL = "https://www.tipsnepal.com/wp-json/zooktirest/v2/posts/3/1";
            var httpClient = new HttpClient();
            var response = await httpClient.GetFromJsonAsync<List<Post>>(URL);
            return View(response);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CallingAPI_MVC/Controllers/TipsNepalController.cs
using CallingAPI_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;

namespace CallingAPI_MVC.Controllers
{
    public class TipsNepalController : Controller
    {
        public IActionResult Index(int id)
        {
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            string json = (new WebClient()).DownloadString("https://www.tipsnepal.com/wp-json/wp/v2/posts");
            var TipsNepalResult = JsonConvert.DeserializeObject(json, typeof(List<TipsNepal>)) as List<TipsNepal>;

            return View(TipsNepalResult);
        }
    }
}

CallingAPI_MVC/Views/Blog/Index.cshtml
@model IEnumerable<Blog>

@{
    var data = ViewBag.Data;
}


@*
    <div>
    @foreach (var item in Model)
    {
    <h1>@item.id</h1>
    <h1>@item.title</h1>
    <h1>@item.date</h1>
    <img src="@item.image_link_small"/>
    <img src="@item.image_link_medium"/>
    <h1>@item.desc</h1>
    }
    </div>*@



@*Blogs section*@


<div class="uk-grid-small uk-child-width-1-3@s uk-padding " uk-grid>
    @foreach (var item in Model)
    {
        <div>
            <div class="uk-card uk-card-default" style="border-radius:6px; ">
                <div class="uk-card-media-top card-img">
                    <a asp-action="Details" asp-route-id="@item.id"><img src="@item.image_link_medium" alt="" style="border-radius: 6px 6px 0px 0px; object-fit:cover"></a>
                </div>
                <div class="uk-card-body">
                    <a asp-action="Details" asp-route-id="@item.id"><h3 class="uk-card-title">@item.title</h3></a>
                </div>
            </div>
        </div>
    }
</div>




@*
    <h2 class="uk-margin-medium-left" style="margin-bottom:-40px; margin-top:20px;">Blogs</h2>
    <div class="uk-grid-small uk-child-width-expand@s uk-margin-top uk-padding" uk-grid>

    @foreach (var item in Model)
    {
    <div>
    <div class="uk-card uk-card-default" style="border-radius:6px; ">
    <div class="uk-card-media-top card-img">
    <a asp-action="Details" asp-route-id="@item.id"><img src="@item.image_link_medium" alt="" style="border-radius: 6px 6px 0px 0px; object-fit:cover"></a>
    </div>
    <div class="uk-card-body">
    <a asp-action="Details" asp-route-id="@item.id"><h3 class="uk-card-title">@item.title</h3></a>
    </div>
    </div>
    </div>
    }
    </div>

*@

CallingAPI_MVC/Views/Home/Index.cshtml
@model List<Post>
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .card img {
        width: 100%;
    }

    .rounded {
        border-radius: 0.25rem !important;
    }

    img {
        max-width: 100% !important;
        height: auto;
    }

    img, svg {
        vertical-align: middle;
    }
</style>
<div class="row g-4 gx-3">

    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <div class="card shadow-sm rounded">
                <a href="@item.Image_link_small">
                    <img src="@item.Image_link_medium" class="default rounded" alt="57 Quality Nepali Names That Start With D">
                </a>
                <div class="p-2 pt-3">
                    <h3 class="card-title"><a href="">@item.Title</a></h3>
                </div>
            </div>
        </div>
    }
</div>

CallingAPI_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CallingAPI_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CallingAPI_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CallingAPI_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipsNepal" asp-action="Index">TipsNepal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CallingAPI_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CallingAPI_MVC/Views/TipsNepal/Index.cshtml
@model IEnumerable<CallingAPI_MVC.Models.TipsNepal>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date_gmt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modified)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modified_gmt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.slug)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.featured_media)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.comment_status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ping_status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sticky)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.template)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.format)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.jetpack_featured_media_url)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_gmt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.modified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.modified_gmt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.slug)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type)
            </td>
            <td>
                @*<a href="@item.link">Test</a>*@
                @Html.DisplayFor(modelItem => item.link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.featured_media)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.comment_status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ping_status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sticky)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.template)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.format)
            </td>
            <td>
                <img src="@item.jetpack_featured_media_url" height="20" width="20" />
                @*@Html.DisplayFor(modelItem => item.jetpack_featured_media_url)*@
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>